backend:
  name: github
  repo: gusbmurphy/Personal-Site

media_folder: static/assets
public_folder: assets

media_library:
  name: cloudinary
  config:
    cloud_name: dtc0i7udk
    api_key: 234775223881751
    multiple: true

collections:
  - name: writing
    label: Writing
    folder: content/writing
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: tags, label: Tags, default: ["news", "games"], widget: "list" }
      - { name: body, label: Body, widget: markdown }
      - { name: "templateKey", widget: "hidden", default: "writing" }
  - name: work
    label: Work
    folder: content/work
    create: true
    fields:
      - { name: date, label: Date, widget: date, dateFormat: "MM.YYYY" }
      - { name: title, label: Title }
      - { name: tags, label: Tags, widget: "list" }
      - name: links
        label: Links
        widget: "list"
        required: false
        fields:
        - { label: Display, name: display, widget: string }
        - { label: URL, name: url, widget: string }
      - { name: shortDesc, label: Short Description, widget: "string" }
      - { name: description, label: Full Description, widget: "markdown" }
      - name: previewImage
        label: PreviewImage
        widget: "image"
        # allow_multiple: false
        media_library:
          config:
            allow_multiple: false
      - name: imageGallery
        label: ImageGallery
        widget: "image"
        # allow_multiple: true
        media_library:
          config:
            allow_multiple: true
      - { name: "templateKey", widget: "hidden", default: "work" }
